from typing import Any, Callable, Dict, Iterable, Optional

class API(object):
    def __init__(self, name: str) -> None: ...
    def route(self, path: str, methods: Iterable[str] | None = ...) -> Callable[..., Any]: ...

def make_response(*, data: Any, status: int = ..., headers: Optional[Dict[str, str]] = ...) -> Any: ...
